# coding: utf-8

"""
    Nature API

    Read/Write Nature Remo  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from nature_api_client.models.air_con_range_modes import AirConRangeModes  # noqa: F401,E501
from nature_api_client.models.button import Button  # noqa: F401,E501


class AirConRange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'modes': 'AirConRangeModes',
        'fixed_buttons': 'list[Button]'
    }

    attribute_map = {
        'modes': 'modes',
        'fixed_buttons': 'fixedButtons'
    }

    def __init__(self, modes=None, fixed_buttons=None):  # noqa: E501
        """AirConRange - a model defined in Swagger"""  # noqa: E501

        self._modes = None
        self._fixed_buttons = None
        self.discriminator = None

        if modes is not None:
            self.modes = modes
        if fixed_buttons is not None:
            self.fixed_buttons = fixed_buttons

    @property
    def modes(self):
        """Gets the modes of this AirConRange.  # noqa: E501


        :return: The modes of this AirConRange.  # noqa: E501
        :rtype: AirConRangeModes
        """
        return self._modes

    @modes.setter
    def modes(self, modes):
        """Sets the modes of this AirConRange.


        :param modes: The modes of this AirConRange.  # noqa: E501
        :type: AirConRangeModes
        """

        self._modes = modes

    @property
    def fixed_buttons(self):
        """Gets the fixed_buttons of this AirConRange.  # noqa: E501


        :return: The fixed_buttons of this AirConRange.  # noqa: E501
        :rtype: list[Button]
        """
        return self._fixed_buttons

    @fixed_buttons.setter
    def fixed_buttons(self, fixed_buttons):
        """Sets the fixed_buttons of this AirConRange.


        :param fixed_buttons: The fixed_buttons of this AirConRange.  # noqa: E501
        :type: list[Button]
        """

        self._fixed_buttons = fixed_buttons

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AirConRange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
