# coding: utf-8

"""
    Nature API

    Read/Write Nature Remo  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from nature_api_client.models.id import Id  # noqa: F401,E501
from nature_api_client.models.image import Image  # noqa: F401,E501


class ApplianceModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'Id',
        'manufacturer': 'str',
        'remote_name': 'str',
        'name': 'str',
        'image': 'Image'
    }

    attribute_map = {
        'id': 'id',
        'manufacturer': 'manufacturer',
        'remote_name': 'remote_name',
        'name': 'name',
        'image': 'image'
    }

    def __init__(self, id=None, manufacturer=None, remote_name=None, name=None, image=None):  # noqa: E501
        """ApplianceModel - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._manufacturer = None
        self._remote_name = None
        self._name = None
        self._image = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if manufacturer is not None:
            self.manufacturer = manufacturer
        if remote_name is not None:
            self.remote_name = remote_name
        if name is not None:
            self.name = name
        if image is not None:
            self.image = image

    @property
    def id(self):
        """Gets the id of this ApplianceModel.  # noqa: E501


        :return: The id of this ApplianceModel.  # noqa: E501
        :rtype: Id
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApplianceModel.


        :param id: The id of this ApplianceModel.  # noqa: E501
        :type: Id
        """

        self._id = id

    @property
    def manufacturer(self):
        """Gets the manufacturer of this ApplianceModel.  # noqa: E501


        :return: The manufacturer of this ApplianceModel.  # noqa: E501
        :rtype: str
        """
        return self._manufacturer

    @manufacturer.setter
    def manufacturer(self, manufacturer):
        """Sets the manufacturer of this ApplianceModel.


        :param manufacturer: The manufacturer of this ApplianceModel.  # noqa: E501
        :type: str
        """

        self._manufacturer = manufacturer

    @property
    def remote_name(self):
        """Gets the remote_name of this ApplianceModel.  # noqa: E501


        :return: The remote_name of this ApplianceModel.  # noqa: E501
        :rtype: str
        """
        return self._remote_name

    @remote_name.setter
    def remote_name(self, remote_name):
        """Sets the remote_name of this ApplianceModel.


        :param remote_name: The remote_name of this ApplianceModel.  # noqa: E501
        :type: str
        """

        self._remote_name = remote_name

    @property
    def name(self):
        """Gets the name of this ApplianceModel.  # noqa: E501


        :return: The name of this ApplianceModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApplianceModel.


        :param name: The name of this ApplianceModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def image(self):
        """Gets the image of this ApplianceModel.  # noqa: E501


        :return: The image of this ApplianceModel.  # noqa: E501
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this ApplianceModel.


        :param image: The image of this ApplianceModel.  # noqa: E501
        :type: Image
        """

        self._image = image

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplianceModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
