# coding: utf-8

"""
    Nature API

    Read/Write Nature Remo  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from nature_api_client.models.id import Id  # noqa: F401,E501


class DeviceCore(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'Id',
        'name': 'str',
        'temperature_offset': 'float',
        'humidity_offset': 'float',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'firmware_version': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'temperature_offset': 'temperature_offset',
        'humidity_offset': 'humidity_offset',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'firmware_version': 'firmware_version'
    }

    def __init__(self, id=None, name=None, temperature_offset=None, humidity_offset=None, created_at=None, updated_at=None, firmware_version=None):  # noqa: E501
        """DeviceCore - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._temperature_offset = None
        self._humidity_offset = None
        self._created_at = None
        self._updated_at = None
        self._firmware_version = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if temperature_offset is not None:
            self.temperature_offset = temperature_offset
        if humidity_offset is not None:
            self.humidity_offset = humidity_offset
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if firmware_version is not None:
            self.firmware_version = firmware_version

    @property
    def id(self):
        """Gets the id of this DeviceCore.  # noqa: E501


        :return: The id of this DeviceCore.  # noqa: E501
        :rtype: Id
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeviceCore.


        :param id: The id of this DeviceCore.  # noqa: E501
        :type: Id
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this DeviceCore.  # noqa: E501


        :return: The name of this DeviceCore.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeviceCore.


        :param name: The name of this DeviceCore.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def temperature_offset(self):
        """Gets the temperature_offset of this DeviceCore.  # noqa: E501


        :return: The temperature_offset of this DeviceCore.  # noqa: E501
        :rtype: float
        """
        return self._temperature_offset

    @temperature_offset.setter
    def temperature_offset(self, temperature_offset):
        """Sets the temperature_offset of this DeviceCore.


        :param temperature_offset: The temperature_offset of this DeviceCore.  # noqa: E501
        :type: float
        """

        self._temperature_offset = temperature_offset

    @property
    def humidity_offset(self):
        """Gets the humidity_offset of this DeviceCore.  # noqa: E501


        :return: The humidity_offset of this DeviceCore.  # noqa: E501
        :rtype: float
        """
        return self._humidity_offset

    @humidity_offset.setter
    def humidity_offset(self, humidity_offset):
        """Sets the humidity_offset of this DeviceCore.


        :param humidity_offset: The humidity_offset of this DeviceCore.  # noqa: E501
        :type: float
        """

        self._humidity_offset = humidity_offset

    @property
    def created_at(self):
        """Gets the created_at of this DeviceCore.  # noqa: E501


        :return: The created_at of this DeviceCore.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this DeviceCore.


        :param created_at: The created_at of this DeviceCore.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this DeviceCore.  # noqa: E501


        :return: The updated_at of this DeviceCore.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this DeviceCore.


        :param updated_at: The updated_at of this DeviceCore.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def firmware_version(self):
        """Gets the firmware_version of this DeviceCore.  # noqa: E501


        :return: The firmware_version of this DeviceCore.  # noqa: E501
        :rtype: str
        """
        return self._firmware_version

    @firmware_version.setter
    def firmware_version(self, firmware_version):
        """Sets the firmware_version of this DeviceCore.


        :param firmware_version: The firmware_version of this DeviceCore.  # noqa: E501
        :type: str
        """

        self._firmware_version = firmware_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceCore):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
